version: "3.8"

services:
  emqx:
    image: emqx/emqx:5.0.13
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_ACL_NOMATCH=allow
      - EMQX_ENABLE_ACL=false
      - EMQX_AUTHORIZATION__NO_MATCH=allow
      - EMQX_AUTHORIZATION__SOURCES=[]
    networks:
      - iot-net

  simulator:
    build: .
    container_name: mqtt-simulator
    restart: unless-stopped
    depends_on:
      - emqx
    environment:
      - BROKER_HOST=emqx
      - BROKER_PORT=1883
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
